name: Multi-Container CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Run Docker Compose
        run: |
          cd Day14
          docker compose up -d --build

      - name: Show Running Containers
        run: docker ps